<a href="https://colab.research.google.com/github/PsorTheDoctor/Sekcja-SI/blob/master/machine_learning/supervised_learning/naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Naiwny klasyfikator bayesowski

In [0]:
!pip install scikit-learn

In [0]:
!pip install --upgrade scikit-learn

### Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import sklearn

np.random.seed(42)
np.set_printoptions(precision=6, suppress=True)
sklearn.__version__

'0.22.2.post1'

### Wygenerowanie danych

In [2]:
pogoda = ['słonecznie', 'deszczowo', 'pochmurno', 'deszczowo', 'słonecznie', 'słonecznie',
          'pochmurno', 'pochmurno', 'słonecznie']
temperatura = ['ciepło', 'zimno', 'ciepło', 'ciepło', 'ciepło', 'umiarkowanie',
               'umiarkowanie', 'ciepło', 'zimno']

spacer = ['tak', 'nie', 'tak', 'nie', 'tak', 'tak', 'nie', 'tak', 'nie']

raw_df = pd.DataFrame(data={'pogoda': pogoda, 'temperatura': temperatura, 'spacer': spacer})
df = raw_df.copy()
df

pogoda   temperatura spacer
0  słonecznie        ciepło    tak
1   deszczowo         zimno    nie
2   pochmurno        ciepło    tak
3   deszczowo        ciepło    nie
4  słonecznie        ciepło    tak
5  słonecznie  umiarkowanie    tak
6   pochmurno  umiarkowanie    nie
7   pochmurno        ciepło    tak
8  słonecznie         zimno    nie

### Przygotowanie danych do modelu

In [3]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['spacer'] = encoder.fit_transform(spacer)
df

pogoda   temperatura  spacer
0  słonecznie        ciepło       1
1   deszczowo         zimno       0
2   pochmurno        ciepło       1
3   deszczowo        ciepło       0
4  słonecznie        ciepło       1
5  słonecznie  umiarkowanie       1
6   pochmurno  umiarkowanie       0
7   pochmurno        ciepło       1
8  słonecznie         zimno       0

In [4]:
df = pd.get_dummies(df, columns=['pogoda', 'temperatura'], drop_first=True)
df

spacer  pogoda_pochmurno  ...  temperatura_umiarkowanie  temperatura_zimno
0       1                 0  ...                         0                  0
1       0                 0  ...                         0                  1
2       1                 1  ...                         0                  0
3       0                 0  ...                         0                  0
4       1                 0  ...                         0                  0
5       1                 0  ...                         1                  0
6       0                 1  ...                         1                  0
7       1                 1  ...                         0                  0
8       0                 0  ...                         0                  1

[9 rows x 5 columns]

In [5]:
data = df.copy()
target = data.pop('spacer')

data

pogoda_pochmurno  ...  temperatura_zimno
0                 0  ...                  0
1                 0  ...                  1
2                 1  ...                  0
3                 0  ...                  0
4                 0  ...                  0
5                 0  ...                  0
6                 1  ...                  0
7                 1  ...                  0
8                 0  ...                  1

[9 rows x 4 columns]

In [6]:
target

0    1
1    0
2    1
3    0
4    1
5    1
6    0
7    1
8    0
Name: spacer, dtype: int64

### Klasyfikator bayesowski

In [14]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB

model1 = GaussianNB()
model2 = MultinomialNB()
model3 = ComplementNB()
model4 = BernoulliNB()
model5 = CategoricalNB()

model1.fit(data, target)
model2.fit(data, target)
model3.fit(data, target)
model4.fit(data, target)
model5.fit(data, target)

CategoricalNB(alpha=1.0, class_prior=None, fit_prior=True)

In [16]:
print(model1.score(data, target))
print(model2.score(data, target))
print(model3.score(data, target))
print(model4.score(data, target))
print(model5.score(data, target))

0.7777777777777778
0.7777777777777778
0.8888888888888888
0.7777777777777778
0.7777777777777778


In [17]:
data.iloc[[0]]

pogoda_pochmurno  ...  temperatura_zimno
0                 0  ...                  0

[1 rows x 4 columns]

In [20]:
model1.predict(data.iloc[[0]])

array([1])

In [11]:
encoder.classes_

array(['nie', 'tak'], dtype='<U3')

In [21]:
encoder.classes_[model1.predict(data.iloc[[0]])[0]]

'tak'

In [27]:
print(model1.predict_proba(data.iloc[[0]]))
print(model2.predict_proba(data.iloc[[0]]))
print(model3.predict_proba(data.iloc[[0]]))
print(model4.predict_proba(data.iloc[[0]]))
print(model5.predict_proba(data.iloc[[0]]))

[[0.000006 0.999994]]
[[0.307692 0.692308]]
[[0.357143 0.642857]]
[[0.228645 0.771355]]
[[0.228645 0.771355]]
